[package]
name = "leaffront-render-glutin"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[dependencies]
glutin = "0.21.1"
image = "0.22.3"

gl = "0.14.0"
libc = "*"

leaffront-core = { path = "../core" }
