[package]
name = "leaffront-render-glutin"
version = "0.1.0"
authors = ["James <1404334+j-selby@users.noreply.github.com>"]
edition = "2018"

[dependencies]
glutin = "0.28.0"
image = "0.25.2"

gl = "0.14.0"
libc = "*"

log = "0.4.22"

leaffront-core = { path = "../core" }
