[package]
name = "leaffront-render-glutin"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[dependencies]
glutin = "0.16.0"
image = "0.15.0"

gl = "0.7.0"
libc = "*"

leaffront-core = { path = "../core" }
