[package]
name = "leaffront-backend-redis"
version = "0.1.0"
authors = ["James <1404334+j-selby@users.noreply.github.com>"]

[dependencies]
leaffront-core = { path = "../core" }

json = "0.11.13"

redis = "0.8.0"
