[package]
name = "leaffront-input-pi"
version = "0.1.0"
authors = ["James <1404334+j-selby@users.noreply.github.com>"]
edition = "2018"

[dependencies]
evdev = "0.13.2"
log = "0.4.28"

leaffront-core = { path = "../core" }

leaffront-render-pi = { path = "../render_pi" }
