[package]
name = "leaffront-input-pi"
version = "0.1.0"
authors = ["James <jselby@jselby.net>"]

[dependencies]
evdev = "0.11.0"

leaffront-core = { path = "../core" }

leaffront-render-pi = { path = "../render_pi" }